#!/bin/sh

# this is external in docker-compose.yml so have to create here
# no error if already exist, just an error message
docker network create jupyterhub_network

# no error if already exist
# create externally so nothing will delete these data volume automatically
docker volume create jupyterhub_data_persistence  # jupyterhub db and cookie secret
