#!/bin/sh -x

apt-get update
apt-get install --yes curl

cd /usr/local/lib/python2.7/dist-packages/threddsclient/

ls -l client.py*

rm -v client.pyc
curl --silent https://raw.githubusercontent.com/bird-house/threddsclient/fa12c369d84b8d1acbf46514a0808cc69bec902e/threddsclient/client.py > client.py

ls -l client.py*

# change logging level to DEBUG
cd /usr/local/lib/python2.7/dist-packages/pavics_datacatalog-0.6.11-py2.7.egg/pavics_datacatalog/wps_processes
curl --silent https://raw.githubusercontent.com/Ouranosinc/PAVICS-DataCatalog/1b81c2e0ad12a3ae32f400d4688cb8abae828fa5/pavics_datacatalog/wps_processes/wps_pavicsearch.py > wps_pavicsearch.py
rm -v wps_pavicsearch.pyc

cd /usr/local/lib/python2.7/dist-packages/pavics
rm -v catalog.pyc
curl --silent https://raw.githubusercontent.com/Ouranosinc/pyPavics/a10d596b6f0b3d70c96cc0cac5356014aac42dab/pavics/catalog.py > catalog.py

# Existing CMD from Dockerfile
cd /
python /home/docker_configs.py && \
    /etc/init.d/apache2 start && tail -f /dev/null
