#!/bin/sh -x

apt-get update
apt-get install --yes curl

cd /usr/local/lib/python2.7/dist-packages/threddsclient/

ls -l client.py*

rm -v client.pyc
curl --silent https://raw.githubusercontent.com/bird-house/threddsclient/fa12c369d84b8d1acbf46514a0808cc69bec902e/threddsclient/client.py > client.py

ls -l client.py*

# change logging level to DEBUG
cd /usr/local/lib/python2.7/dist-packages/pavics_datacatalog-0.6.11-py2.7.egg/pavics_datacatalog/wps_processes
perl -pe 's/logger.setLevel\(logging.INFO\)/logger.setLevel\(logging.DEBUG\)/' -i wps_pavicsearch.py
rm -v wps_pavicsearch.pyc

cd /usr/local/lib/python2.7/dist-packages/pavics
rm -v catalog.pyc
curl --silent https://raw.githubusercontent.com/Ouranosinc/pyPavics/19a10525441c9808ecae4799a6a573005ef1a37f/pavics/catalog.py > catalog.py

# Existing CMD from Dockerfile
cd /
python /home/docker_configs.py && \
    /etc/init.d/apache2 start && tail -f /dev/null
