#!/bin/sh

backup_application() {
  _do_backup() {
    ${BIRDHOUSE_EXE} --quiet compose run --rm -v ${BIRDHOUSE_BACKUP_VOLUME}:/backup postgres sh -c 'mkdir -p /backup/hummingbird; PGPASSWORD=${POSTGRES_PASSWORD} pg_dump -h postgres -U ${POSTGRES_USER} -d hummingbird -Fc > /backup/hummingbird/postgres.dump'
  }
  do_backup 'hummingbird postgres database' _do_backup 'hummingbird' 
}

restore_application() {
  _do_restore() { 
    ${BIRDHOUSE_EXE} --quiet compose run --rm -v ${BIRDHOUSE_BACKUP_VOLUME}:/backup postgres sh -c 'export PGPASSWORD=${POSTGRES_PASSWORD}; dropdb -h postgres -U ${POSTGRES_USER} hummingbird; pg_restore -h postgres -U ${POSTGRES_USER} -C -d postgres /backup/hummingbird/postgres.dump'
  }
  do_restore 'hummingbird postgres database' _do_restore 'hummingbird' 'hummingbird'
}
