version: 2

updates:
  - package-ecosystem: github-actions
    directory: /.github/workflows
    commit-message:
      include: scope
      # Skip comment specifically for Jenkins CI builds on CRIM infrastructure
      # [skip ci] cannot be used here in order for auto-accept-ci-changes.yml to function
      prefix: "[skip jenkins] "
    schedule:
      interval: "quarterly"
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          # only group patch and minor updates which will allow the dependabot-auto-approve job to approve and
          # merge these updates without having to wait for approval if the group also includes a major update.
          - patch
          - minor
    cooldown:
      default-days: 7

  - package-ecosystem: pip
    directories:
      - /.github
      - /tests
    schedule:
      interval: "quarterly"
    groups:
      python:
        patterns:
          - "*"
        update-types:
          - patch
          - minor
          - major
    cooldown:
      default-days: 7
