version: 2

updates:
  - package-ecosystem: github-actions
    directory: /.github/workflows
    commit-message:
      include: scope
      prefix: "[skip ci]"
    schedule:
      interval: "quarterly"
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - patch
          - minor
          - major
    cooldown:
      default-days: 7

  - package-ecosystem: pip
    directories:
      - /.github
      - /tests
    schedule:
      interval: "quarterly"
    groups:
      python:
        patterns:
          - "*"
        update-types:
          - patch
          - minor
          - major
    cooldown:
      default-days: 7
