# conda env create -f environment-dev.yml
name: birdhouse-deploy
channels:
  - conda-forge
  - nodefaults  # to avoid installing the default packages that come with conda
dependencies:
  - make

  # for generating requirements.txt with hashes
  - pip-tools

  - pip
  - pip:
    - -r .github/requirements_ci.txt
