#!/bin/sh

backup_application() {

  _do_backup() {
    ${BIRDHOUSE_EXE} --quiet compose run --rm -v ${BIRDHOUSE_BACKUP_VOLUME}:/backup postgres sh -c 'mkdir -p /backup/postgres; PGPASSWORD=${POSTGRES_PASSWORD} pg_dump -h postgres -U ${POSTGRES_USER} -d ${POSTGRES_DB} -Fc > /backup/postgres/postgres.dump'
  }
  do_backup "postgres ${BIRDHOUSE_POSTGRES_DB} database" _do_backup
}

restore_application() {
  _do_restore() { 
    ${BIRDHOUSE_EXE} --quiet compose run --rm -v ${BIRDHOUSE_BACKUP_VOLUME}:/backup postgres sh -c 'export PGPASSWORD=${POSTGRES_PASSWORD}; dropdb -h postgres -U ${POSTGRES_USER} ${POSTGRES_DB}; pg_restore -h postgres -U ${POSTGRES_USER} -C -d postgres /backup/postgres/postgres.dump'
  }
  do_restore "postgres ${BIRDHOUSE_POSTGRES_DB} database" _do_restore 'postgres'
}
