#!/bin/sh

THIS_FILE="$(readlink -f "$0" || realpath "$0")"
THIS_DIR="$(dirname "$THIS_FILE")"
COMPOSE_DIR="$THIS_DIR/../.."

if [ -f "${COMPOSE_DIR}/scripts/read-configs.include.sh" ]; then
  . "${COMPOSE_DIR}/scripts/read-configs.include.sh"

  # resolve GEOSERVER_DATA_DIR
  read_configs
fi

if [ ! -f "${GEOSERVER_DATA_DIR}/global.xml" ]; then
  log INFO "fix GeoServer data dir permission on first run only, when data dir do not exist yet."
  FIRST_RUN_ONLY=1 "${COMPOSE_DIR}"/deployment/fix-geoserver-data-dir-perm
fi
