#!/bin/sh

if [ ! -f "${GEOSERVER_DATA_DIR}/global.xml" ]; then
  eval "$(${BIRDHOUSE_EXE} configs --print-log-command)"
  log INFO "fix GeoServer data dir permission on first run only, when data dir do not exist yet."
  FIRST_RUN_ONLY=1 "${COMPOSE_DIR}/deployment/fix-geoserver-data-dir-perm"
fi
