#!/bin/sh -x

CONF_FILE="/usr/local/tomcat/conf/server.xml"

# Configure proxy support as per
# https://tomcat.apache.org/tomcat-8.0-doc/config/http.html#Proxy_Support
# This config automate manual step to set proxy base url in Geoserver UI:
# https://docs.geoserver.org/2.9.3/user/configuration/globalsettings.html#proxy-base-url
if ! grep " scheme=\"https\" proxyName=\"${PAVICS_FQDN_PUBLIC}\" proxyPort=\"443\" " $CONF_FILE; then
    ORIGINAL_FILE="${CONF_FILE}.bak.proxy.$$"
    cp -v $CONF_FILE $ORIGINAL_FILE
    sed -i "s/<Connector /<Connector scheme=\"https\" proxyName=\"${PAVICS_FQDN_PUBLIC}\" proxyPort=\"443\" /g" $CONF_FILE
    diff -u $ORIGINAL_FILE $CONF_FILE
fi

# chain existing entrypoint
catalina.sh run
