{
 "title": "Docker and system monitoring",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Prometheus)",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "containergroup", "label": "Container Group", "query": "label_values(container_group)" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "server", "label": "Node", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "min((node_filesystem_size_bytes{fstype=~\"xfs|ext4\"} - node_filesystem_free_bytes{fstype=~\"xfs|ext4\"} )/ node_filesystem_size_bytes{fstype=~\"xfs|ext4\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100)"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~'$server:.*'} - node_memory_SwapFree_bytes{instance=~'$server:.*'}) / node_memory_SwapTotal_bytes{instance=~'$server:.*'} * 100"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1" }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[$interval])) * 100",
     "legendFormat": "host"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"^node_load.*\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Used Disk Space",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes * 100"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal - node_memory_MemAvailable",
     "legendFormat": "Unavailable Memory"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(node_disk_bytes_read[$interval])) by (device)",
     "legendFormat": "OUT on /{{device}}"
    },
    {
     "expr": "sum(rate(node_disk_bytes_written[$interval])) by (device)",
     "legendFormat": "IN on /{{device}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[$interval])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Swap per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_swap{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}