#!/bin/sh

backup_logs() {
  _do_backup() {
    docker run --rm \
               -v ${BIRDHOUSE_BACKUP_VOLUME}:/backup \
               -v thredds_persistence:/persist \
               "${BASH_IMAGE}" \
               sh -c 'cp -a /persist/logs /backup/thredds-logs'
  }
  do_backup 'thredds application logs' _do_backup 'thredds'
}

restore_logs() {
  BIRDHOUSE_BACKUP_RESTORE_NO_CLOBBER=true do_restore 'thredds application logs' : 'thredds-logs'
}
