#!/bin/sh

for userpass in $JUPYTERHUB_USERS_PASS; do
    useronly="`echo "$userpass" | cut -d: -f1`"
    adduser --disabled-password --gecos "" $useronly
    echo "$userpass" | chpasswd
done

# start jupyterhub
jupyterhub
