#!/bin/sh -x

# conda activate < some env that has sphinx installed, like finch-docs for example >

# This line copied from RtD build log.
python -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html
