#!/bin/sh
#
# Extract Jupyter users from Magpie DB so we can send announcements to all
# Jupyter users.
#
# Sample output:
#
# $ ./scripts/extract-jupyter-users-from-magpie-db  > /tmp/out
# + echo SELECT email,user_name FROM users ORDER BY email
# + docker exec -i postgres-magpie psql -U postgres-magpie magpiedb
#
# $ cat /tmp/out
#          email          |   user_name
# ------------------------+---------------
#  admin-catalog@mail.com | admin-catalog
#  admin@mail.com         | admin
#  anonymous@mail.com     | anonymous
#  authtest@example.com   | authtest
# (4 rows)


THIS_FILE="`realpath "$0"`"
THIS_DIR="`dirname "$THIS_FILE"`"
COMPOSE_DIR="`dirname "$THIS_DIR"`"

if [ -f "${COMPOSE_DIR}/read-configs.include.sh" ]; then
    . "${COMPOSE_DIR}/read-configs.include.sh"

    # Get POSTGRES_MAGPIE_USERNAME, MAGPIE_DB_NAME.
    read_configs
fi

set -x

echo "SELECT email,user_name FROM users ORDER BY email" | docker exec -i postgres-magpie psql -U $POSTGRES_MAGPIE_USERNAME $MAGPIE_DB_NAME
