#!/bin/sh
#
# Extract Jupyter users from Magpie DB so we can send announcements to all
# Jupyter users.
#
# Sample output:
#
# $ ./scripts/extract-jupyter-users-from-magpie-db  > /tmp/out
# + echo SELECT email,user_name FROM users ORDER BY email
# + docker exec -i postgres-magpie psql -U postgres-magpie magpiedb
#
# $ cat /tmp/out
#          email          |   user_name
# ------------------------+---------------
#  admin-catalog@mail.com | admin-catalog
#  admin@mail.com         | admin
#  anonymous@mail.com     | anonymous
#  authtest@example.com   | authtest
# (4 rows)


THIS_FILE="`realpath "$0"`"
THIS_DIR="`dirname "$THIS_FILE"`"
COMPOSE_DIR="`dirname "$THIS_DIR"`"

if [ -f "$COMPOSE_DIR/default.env" ]; then
    # Need to source this one first, else sourcing env.local might not work.
    . "${COMPOSE_DIR}/default.env"
fi

if [ -f "$COMPOSE_DIR/env.local" ]; then
    # Get POSTGRES_MAGPIE_USERNAME, MAGPIE_DB_NAME.
    . "${COMPOSE_DIR}/env.local"
fi

set -x

echo "SELECT email,user_name FROM users ORDER BY email" | docker exec -i postgres-magpie psql -U $POSTGRES_MAGPIE_USERNAME $MAGPIE_DB_NAME
