#!/bin/sh

backup_application() {
  _do_backup() {
    ${BIRDHOUSE_EXE} --quiet compose run --rm -v ${BIRDHOUSE_BACKUP_VOLUME}:/backup postgres sh -c 'mkdir -p /backup/finch; PGPASSWORD=${POSTGRES_PASSWORD} pg_dump -h postgres -U ${POSTGRES_USER} -d finch -Fc > /backup/finch/postgres.dump'
  }
  do_backup 'finch postgres database' _do_backup 'finch' 
}

restore_application() {
  _do_restore() { 
    ${BIRDHOUSE_EXE} --quiet compose run --rm -v ${BIRDHOUSE_BACKUP_VOLUME}:/backup postgres sh -c 'export PGPASSWORD=${POSTGRES_PASSWORD}; dropdb -h postgres -U ${POSTGRES_USER} finch; pg_restore -h postgres -U ${POSTGRES_USER} -C -d postgres /backup/finch/postgres.dump'
  }
  do_restore 'finch postgres database' _do_restore 'finch' 'finch'
}
