#!/bin/bash
# Deploy data from git repo(s) to local folder(s).
# This script is run directly on a specific image (such as pavics/crim-jupyter-eo or pavics/crim-jupyter-nlp).
# It will be used to download and update the different tutorial notebooks associated with a specific image.
#
# This is meant to be run on the same host running PAVICS.
#
# The data details is specified in a yaml config file (TEMPLATE_CONFIG_YML), using this format :
# - repo_url: path to the github repo (ex.: https://github.com/crim-ca/pavics-jupyter-images)
#   branch: name of the branch containing the required version of the data
#   source_path: path of the desired file or folder in the source repo
#   dest_dir: directory where the data will be copied to in the specific image where the script is run
#
# One or more entries respecting this format can be added to the yaml file, in order to download multiple file/folders.
#
# Setting environment variable DEPLOY_DATA_LOGFILE='/path/to/logfile.log'
# will redirect all STDOUT and STDERR to that logfile so this script will be
# completely silent.

if [ ! -z "$DEPLOY_DATA_LOGFILE" ]; then
    exec >>$DEPLOY_DATA_LOGFILE 2>&1
fi

if [ -z "$NOTEBOOK_DEST_DIR" ]; then
    echo "ERROR: NOTEBOOK_DEST_DIR variable has not been set" 1>&2
    exit 2
fi

START_TIME="`date -Isecond`"
echo "==========
deploy-data-specific-image START_TIME=$START_TIME"

CONFIG_YML_PATH="$1"
if [ -z "$CONFIG_YML_PATH" ]; then
    echo "ERROR: missing config.yml file" 1>&2
    exit 2
fi

# Checks if the config has a required parameter value, takes the string name of the env variable to evaluate as input.
# Empty value could mean typo in the keys in the config file.
ensure_not_null() {
    if [ "${!1}" = null ]; then
        echo "ERROR: empty $1 value found in the config file" 1>&2
        exit 1
    fi
}

# Check installation of required package to read yaml files
if ! command -v yq &> /dev/null; then
    echo "ERROR: missing yq package installation" 1>&2
    exit 1
fi

# Find how many entries are in the config file
CONFIG_LIST_LENGTH="`yq -r '. | length' $CONFIG_YML_PATH`"

if [ -z $CONFIG_LIST_LENGTH ]; then
    echo "ERROR: empty config file" 1>&2
    exit 1
fi

for ((i=0;i<$CONFIG_LIST_LENGTH;i++)); do
    # Extract data from config
    GIT_REPO="`yq -r .[$i].repo_url $CONFIG_YML_PATH`"
    ensure_not_null "GIT_REPO"

    BRANCH="`yq -r .[$i].branch $CONFIG_YML_PATH`"
    ensure_not_null "BRANCH"

    SOURCE_PATH="`yq -r .[$i].source_path $CONFIG_YML_PATH`"
    ensure_not_null "SOURCE_PATH"

    FULL_URL=$GIT_REPO/branches/$BRANCH/$SOURCE_PATH

    echo "Extracting ${FULL_URL} to ${NOTEBOOK_DEST_DIR}"

    # Download the data from github and copy it to the destination directory
    svn export --force $FULL_URL $NOTEBOOK_DEST_DIR
done

echo "notebookdeploy finished   END_TIME=`date -Isecond`"

# vi: tabstop=8 expandtab shiftwidth=4 softtabstop=4
