#!/bin/sh -e
# Allow geoserver container write perm on its data dir.
#
# Geoserver container runs with hardcoded uid 1000 and gid 10001.
#
# Set env var FIRST_RUN_ONLY to only execute this script once, before first
# startup of Geoserver.  If Geoserver has already run at least once, file
# global.xml will exist and this script will not execute.  Without
# FIRST_RUN_ONLY, this script will always execute.

THIS_FILE="$(readlink -f "$0" || realpath "$0")"
THIS_DIR="$(dirname "${THIS_FILE}")"
COMPOSE_DIR="${COMPOSE_DIR:-$(dirname "${THIS_DIR}")}"
BIRDHOUSE_EXE="${COMPOSE_DIR}/../bin/birdhouse"

if [ -z "${1:-"${GEOSERVER_DATA_DIR}"}" ] || [ -z "${BASH_IMAGE}" ]; then
    eval "$(${BIRDHOUSE_EXE} configs --print-config-command)"
    read_configs
fi

set -x

DATA_DIR="${1:-"${GEOSERVER_DATA_DIR}"}"

docker run --rm --name fix-geoserver-data-dir-perm \
    --volume "${DATA_DIR}":/datadir \
    --env FIRST_RUN_ONLY \
    "${BASH_IMAGE}" \
    bash -xc 'if [ -z "$FIRST_RUN_ONLY" -o ! -f /datadir/global.xml ]; \
    then chown -R 1000:10001 /datadir; else echo "No execute."; fi'
