#!/bin/sh
# Script to deploy the logrotate config.
#
# Will deploy:
#
# * logrotate config for various automation scripts output
#   (/etc/logrotate.d/PAVICS-deploy)
#

usage() {
    echo "USAGE: $0 pavics-checkout owner-pavics-checkout"
}

if [ -z "$1" ]; then
    echo "ERROR: please supply mandatory arguments" 1>&2
    usage
    exit 2
fi

REPO_ROOT="`realpath "$1"`"; shift  # path to PAVICS checkout
REPO_OWNER="$1"; shift  #  user owning (have write access) the PAVICS checkout

COMPOSE_DIR="$REPO_ROOT/birdhouse"
. $COMPOSE_DIR/read-configs.include.sh

# read LOGROTATE_CONF_EXTRA for envsubst
read_configs

LOGROTATE_CONF_TEMPLATE="$COMPOSE_DIR/deployment/PAVICS-deploy.logrotate.template"

if [ ! -e "$LOGROTATE_CONF_TEMPLATE" ]; then
    echo "ERROR: bad/wrong pavics-checkout '$REPO_ROOT' " 1>&2
    usage
    exit 2
fi


set -x

sudo mkdir -p /var/log/PAVICS
sudo chown $REPO_OWNER /var/log/PAVICS

LOGROTATE_FILE="/etc/logrotate.d/PAVICS-deploy"
cat $LOGROTATE_CONF_TEMPLATE | envsubst | sudo tee $LOGROTATE_FILE
sudo chown root:root $LOGROTATE_FILE
sudo chmod 644 $LOGROTATE_FILE
