#!/bin/sh
# Script to deploy the logrotate config.
#
# Will deploy:
#
# * logrotate config for various automation scripts output
#   (/etc/logrotate.d/birdhouse-deploy)
#

usage() {
    echo "USAGE: $0 pavics-checkout owner-pavics-checkout"
}

if [ -z "$1" ]; then
    echo "ERROR: please supply mandatory arguments" 1>&2
    usage
    exit 2
fi

REPO_ROOT="`realpath "$1"`"; shift  # path to PAVICS checkout
REPO_OWNER="$1"; shift  #  user owning (have write access) the PAVICS checkout

if [ ! -e "$REPO_ROOT/birdhouse/deployment/PAVICS-deploy.logrotate" ]; then
    echo "ERROR: bad/wrong pavics-checkout '$REPO_ROOT' " 1>&2
    usage
    exit 2
fi


set -x

sudo mkdir -p /var/log/PAVICS
sudo chown $REPO_OWNER /var/log/PAVICS

LOGROTATE_FILE="/etc/logrotate.d/PAVICS-deploy"
sudo cp -v $REPO_ROOT/birdhouse/deployment/PAVICS-deploy.logrotate $LOGROTATE_FILE
sudo chown root:root $LOGROTATE_FILE
sudo chmod 644 $LOGROTATE_FILE
