#!/bin/sh
# Script to deploy the logrotate config.
#
# Will deploy:
#
# * logrotate config for various automation scripts output
#   (/etc/logrotate.d/Birdhouse-deploy)
#

usage() {
    echo "USAGE: $0 birdhouse-checkout owner-birdhouse-checkout"
}

if [ -z "$1" ]; then
    echo "ERROR: please supply mandatory arguments" 1>&2
    usage
    exit 2
fi

REPO_ROOT="`realpath "$1"`"; shift  # path to Birdhouse checkout
REPO_OWNER="$1"; shift  #  user owning (have write access) the Birdhouse checkout

if [ ! -e "$REPO_ROOT/birdhouse/deployment/birdhouse-deploy.logrotate" ]; then
    echo "ERROR: bad/wrong birdhouse-checkout '$REPO_ROOT' " 1>&2
    usage
    exit 2
fi

. "${REPO_ROOT}/birdhouse/read-configs.include.sh"

read_basic_configs_only

set -x

sudo mkdir -p "${BIRDHOUSE_LOG_DIR}"
sudo chown $REPO_OWNER "${BIRDHOUSE_LOG_DIR}"

LOGROTATE_FILE="/etc/logrotate.d/Birdhouse-deploy"
sudo cp -v $REPO_ROOT/birdhouse/deployment/birdhouse-deploy.logrotate $LOGROTATE_FILE
sudo chown root:root $LOGROTATE_FILE
sudo chmod 644 $LOGROTATE_FILE
