services:
  s3:
    image: ${S3_IMAGE}
    container_name: s3
    volumes:
      - ${S3_DATA_STORE}:/data
    environment:
      ROOT_ACCESS_KEY: ${S3_ROOT_ACCESS_KEY}
      ROOT_SECRET_KEY: ${S3_ROOT_SECRET_KEY}
    # Note: the sidecar is necessary because the docker container does not support xattrs
    # Note: the --health flag is necessary to enable the /health endpoint in order to check the health of the server
    # Note: the --bucketlinks flag allows versitygw to treat symlinks as buckets (needed when mounting external data to buckets, e.g. thredds)
    command: ["--port", ":3000", "--health", "/health", "posix", "--sidecar=/data/meta", "--bucketlinks", "/data/data"]
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s

  s3-cli:
    image: ${S3_CLI_IMAGE}
    container_name: s3-cli
    # setting a profile ensures that this is not run by default with `birdhouse compose up`
    # instead, this is intended to be called later on with `birdhouse compose run s3-cli`
    profiles:
      - task
    environment:
      AWS_ACCESS_KEY_ID: ${S3_ROOT_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${S3_ROOT_SECRET_KEY}
      AWS_DEFAULT_REGION: us-east-1  # This is the default region that the s3 service will use. It must be explicitly set for aws cli
      AWS_ENDPOINT_URL: http://s3:3000
