name: Dependabot CI Updates

on:
  pull_request:
    branches:
      - master
    paths:
      - .github/**/*.yml
    types:
      - opened
      - synchronize

permissions:
  contents: read

jobs:
  dependabot-auto-approve:
    name: Auto-approve and auto-merge safe Dependabot updates for GitHub Actions
    runs-on: ubuntu-latest
    environment: automation
    if: >
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      contains(github.event.pull_request.labels.*.name, 'ci/operations')
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Generate GitHub App token
        id: token_generator
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          app-id: ${{ secrets.BIRDHOUSE_HELPER_BOT_ID }}
          private-key: ${{ secrets.BIRDHOUSE_HELPER_BOT_KEY }}

      - name: Fetch Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98 # v3.1.0
        with:
          github-token: ${{ steps.token_generator.outputs.token }}

      - name: Stop workflow if not minor update or patch update
        id: skip-condition
        if: >
          steps.dependabot-metadata.outputs.update-type == 'version-update:semver-major'
        run: |
          echo "Not a minor or patch update; Skipping auto-approval."
          echo "skip=true" >> $GITHUB_OUTPUT

      - name: Checkout Repository
        if: steps.skip-condition.outputs.skip != 'true'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.token_generator.outputs.token }}
          persist-credentials: false

      - name: Approve Changes
        if: >
          steps.skip-condition.outputs.skip != 'true' &&
          !contains(github.event.pull_request.labels.*.name, 'approved')
        run: |
          gh pr review --approve "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ steps.token_generator.outputs.token }}
          PR_URL: ${{github.event.pull_request.html_url}}

      - name: Enable auto-merge on Pull Request
        if: steps.skip-condition.outputs.skip != 'true'
        run: |
          gh pr merge --auto --merge "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ steps.token_generator.outputs.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}